import os
import sys

swiftExt = '.swift'
pathToOperationsFolder = '../Source/Operations'
pathToOperationsFile = '../Source/Operations/Operations.swift'

lineTemplate = '        case "{name}": return {name}()'
template = '''// THIS FILE IS AUTOMATICALLY GENERATED BY /framework/GenerateOperationsSource.py
import Foundation
import GPUImage

class Operations {

    init(){ }

    func get(name: String) -> BasicOperation? {
        switch name {
        //E.g, case "BoxBlur": return BoxBlur()
%s
        default: return nil
        }
    }

}'''

if not os.path.isdir( pathToOperationsFolder ):
    print 'Run this script from the framework/Scripts folder.'
    sys.exit()

operations = [ path[:-len(swiftExt)] for path in os.listdir(pathToOperationsFolder) if path.endswith(swiftExt) ]
switchCases = [ lineTemplate.format(name=op) for op in operations ]
fileContents = template % '\n'.join(switchCases)

output = file(pathToOperationsFile, 'w')
output.write( fileContents )
output.close()

print "Generated " + pathToOperationsFile
